---
title: Vinegar and cornstarch are the Secrets to Perpetually Moist Chocolate Cake
author: ''
date: '2021-02-08'
slug: []
categories: ["Recipes","Baking"]
tags: ["Recipes","Baking"]
subtitle: 'Vinegar stabilizes egg whites, increasing emulsion. Starch traps water, preventing dry baked goods over time. Baking soda reacts with vinegar to produce carbon dioxide and water during the cooking process.'
summary: 'Vinegar stabilizes egg whites, increasing emulsion. Starch traps water, preventing dry baked goods over time. Baking soda reacts with vinegar to produce carbon dioxide and water during the cooking process.'
authors: ["Jesse Islam"]
lastmod: '2021-02-08T13:59:13-05:00'
featured: no
image:
  placement: 1
  caption: "Chocolate cake with caramel soak - By Jesse"
  focal_point: "Center"
  preview_only: false
  alt_text: An optional description of the image for screen readers.
projects: ["Recipes"]
---

## Give the people cake

I'm tired of dry cake. This led to the creation of the following recipe. After some extensive research, I decided upon two main ingredients that can be used in any baking endeavor that's too dry for your liking.

## The science

This recipe is a slight edit on Adam Ragusea's [Recipe for chocolate cake](https://www.youtube.com/watch?v=mKWNLDn93YU).

In another video Adam talks about the [benefits of starches](https://www.youtube.com/watch?v=4Sjv3LRVubo) in baked goods at length. In summary, starches can form 3 dimensional structures while being cooked that prevent water from escaping during the cooking process. The ability of water to make your cake rise will dampen, but the result is a dense, moist cake that will last for a week without drying (if it lasts that long). Adam interviews some interesting people in his starch video, it's worth a watch.

The other ingredient is vinegar. There are two main benefits to vinegar and I wanted to make use of both. The first benefit is the gentle denaturation of proteins. If you ever saw [tempering](https://www.youtube.com/watch?v=ezencQbQrvc), or how a [creme brul&#233;](https://www.youtube.com/watch?v=3vib5idIADs) is made, you'll notice that eggs are sensitive to sudden changes in temperature, making them curdle. Curdling occurs due to the denaturation of proteins, occuring at a fast rate. Ideally, we gently denature the proteins before they get tossed in the oven. How? with acid!

Vinegar is a gentle acid that can slowly denature egg whites while you whip them, increasing the stability of this emulsifier. This way, you prevent the "drying out" we get from cooking egg whites too fast. We also get a more stable egg white, resulting in a better emulsion of water and fat in our batter.

The second benefit of vinegar is as a leavening agent. By adding a bit more baking soda to your recipe: 

1. The acidic taste from the vinegar will be cancelled out.
2. You get some carbon dioxide increasing the air in your cake.
3. The equation results in water during the cooking process, making pockets of moisture to form while cooking.

Talk about a magic ingredient. I noticed people use mayonnaise in their recipes as well. I think that the benefit lies in its high fat content and very stable mixture (when's the last time your store bought mayonnaise split). There's also trace amounts of vinegar that remain, so I'm sure the reactions with baking soda are occurring to some extent.

These properties are not restricted to cakes by the way. I'm going to be developing other recipes to see just what I can do with these concepts. Cooking is just a laboratory experiment you can eat.

## The recipe

### Ingredients:

*Just so you know, none of these are hard rules. go by feel, experiment and you should be good to go. Want more vinegar magic? 1/4 tsp baking soda to 1 tbsp vinegar is a pretty [balanced ratio](https://chemistry.stackexchange.com/questions/24475/what-ratio-of-bicarb-to-vinegar-do-i-need-in-order-for-the-result-to-be-ph-neutr) to prevent too much of either side.*

- 1 cup milk 240g.
- 1 cup cocoa powder.
- 1 chocolate bar (100g). Whatever kind you like to eat. 
- 1.5 cups sugar.
- 2/3 cup vegetable oil.
- ~1 cup sour cream (one of those small tubs you can buy is plenty, approx. 8Oz).
- 4 eggs.
- 1 tsp vanilla.
- 1 cup flour.
- 1/8 cup cornstarch.
- 3/4 teaspoon baking soda.
- 1/2 teaspoon baking powder.
- 1/2 teaspoon salt.
- 1 tbsp vinegar.

### Steps
0. Set the oven to 350F.
1. Add milk to a pot and bring to the first bubble you see in the center. Take off heat.
2. Whisk in cocoa powder. I usually do this a spoonful at a time. If your mix is looking like a glaze, you're good. If you add too much cocoa powder and it looks like cookie dough, you went too far. Just add some more milk and you'll be ok.
3. Chop and dump your chocolate bar of choice in while the milk is still warm. you want this to melt down.
4.  1.5 cup sugar into the pot. Depending how sweet you like the cake you can add more or less. Though sugar makes cakes moist, it doesn't matter too much for us.
5. Cup of sour cream into pot. I'm a fan of the acidic, milky flavor this brings to the cake.
6. Cup of oil into pot.
7. vanilla if you got.
8. 4 egg yolks into the pot.
9. Mix it all together until as smooth as you can make it, then let it sit a bit. Don't worry about cocoa clumps if you added too much cocoa powder into the mix during step 1.
10. Beat egg whites with vinegar until soft peaks form.
11. Mix all purpose flour with cornstarch, baking powder, baking soda and salt.
12. Add dry mix to pot and fold until combined.
13. prep baking tin. I use aluminum foil to line the baking vessel, but use whatever technique you like.
14. MAKE SURE the oven is set to 350F. From this point on you want to work as efficiently as possible.
15. Fold soft peak egg whites into batter. You can do some of the egg whites first, then dump the rest but honestly you lose very little air doing it all at once. Fold until no more visible streaks of eggwhite.
15. Pour into the baking vessel. Even out the batter in your baking vessel.
16. 350 for 30 min. You may need more or less time depending on how deep the baking vessel is. A flatter cake is less of an issue here.

The cake is done. I don't know when this cake gets dry because its always finished within a week. As there is higher moisture in this cake, I recommend refrigerating it to prevent microorganism growth. (bacteria prefer moist cake too)

I usually add a [caramel sauce](https://www.youtube.com/watch?v=uO872zbBdNU) across the middle of this chocolate cake after cutting it into layers. Its like a milk soak, except it adds a more complex flavor profile. You do you.
