---
title: Coffee for Two
author: ''
date: '2021-02-09'
slug: []
categories: ["Short Stories"]
tags: ["Short Stories"]
subtitle: ''
summary: ''
authors: ["Jesse Islam"]
lastmod: '2021-02-09T18:21:42-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: ["Short Stories"]
---

The alarm clock rang for a minute by the time Jack finally knocked it off the night stand on his right. The batteries fell out, and he cursed. It happens every other morning, but for some reason his body doesn't listen until a few minutes after waking. He pats around the left side of his bed looking for Jennifer's face. When he finds it, she bites him. He's disturbed the beast in her slumber and paid dearly. To appease the beast he wakes up and heads to the kitchen to make breakfast.

He doesn't eat breakfast, but makes Jennifer coffee every morning. Some would believe this is an act of kindness, but to him its an act of self preservation. As much as he cares for her, he avoids the pre-coffee Jennifer aside from when he wishes to tease her. he takes the pre-portioned cup of ground coffee and puts it in the coffee maker, fills the water and presses the button with the big cup. he steps by the window taking in the scenery. 

Its been 3 years since they started living together. At first, it was out of necessity because neither could afford rent alone. But eventually, they couldn't imagine life any other way. The machine let out a sigh, telling him the coffee was done. He took the cup and headed back to the room. He placed the cup on the coaster on her night stand and stood there for a bit taking in how serene she looked. She complains about the wrinkles near her eyes and buys into all sorts of nonsense claiming to rejuvenate skin. To Jack, those wrinkles are proof of effort she puts into her daily life, and proof that she's smiling. Jack takes pride in the fact that he gets to be there every step of the way. To him, the best way to start the day is on a sour note. 

Her skin on her face is soft but breaks out easily. So she forbids him from touching her face all that often. When shes awake she could dodge on instinct  but when she's asleep...

Jack pinched her cheeks and started pulling. the faces she makes while half asleep are hilarious, but she quickly wakes up does the same to him. Her Eyes are watery first thing in the morning and her hair slightly matted. Aside from the morning breath, its a sight he looks forward to every morning. 

Jennifer rubbed her eyes while reaching for her cup of coffee without looking. Jack's eyes looked content while his mouth turned sour. "It pisses me off that you just assume the coffee is gonna be there every morning". "well, it pisses me off that you need to do one mean thing for every nice thing you do". Here eyes were barely open, and she could retort without pause. 

Jack has this belief of balance, that doing too many good things creates this debt that must be repaid. To counter this, he usually does something stupid or even inconsiderate. Its never an equivalent exchange, however. Just enough to make the good thing he did seem minuscule.

While she sat there with her cup of coffee in her hands, he pressed his hands on both cheeks making her pucker, gave her a kiss and picked her off the bed. " Go take a shower you smell horrible".

Her eyes shot open and she punched him, taking another sip of her coffee before taking a change of clothes with her into the bathroom. To Jack, she didn't really smell bad at all. If anything, there's a natural sent she had that made him feel comfortable. But he also knew that if he let her, she'd take the entire day off because of how comfortable she was in the morning. He knew things that bothered her, and one thing was how she smelled. Jack has a sensitive nose, which is great when cooking but horrible in most other situations. Because of this heightened sense, Jen tries to smell as good as she can to keep him happy. He knows this, though she's never told him. And she knows he knows, though they never acknowledge it. 

As soon as the room was cleaned and he was getting ready to head out, she came out of the shower and walked down the hallway as if she where a runway model. She clearly wanted to be praised, so jack snickered instead. This annoyed her, so she turned to their room and got into the bed Jack just finished making. She cocooned her self within the duvet making it impossible for him to get her out. He got a bucket of water and poured it onto the duvet. Not enough to wet the bed as that would be uncomfortable tonight, but enough to wet the Duvet. " I was gonna clean that later today anyway". She got out of bed defeated, and headed to the kitchen. 

As she looked out the window, she took in the views. The streets were empty, they have been for the last 10 years. Jack was the first person Jen had seen in a long time, and luckily he was someone she could eventually trust.

"I'll be heading out to get supplies for the week." he told her, hugging her from behind. "I haven't had a peaceful morning in the past 3 years" she told him, not trying to fight out of his arms or one up him for the first time today. 

Jack's eyes looked grateful, wishing he could stay by her side all day. "Good to know the job I signed up for is panning out". She rolled her eyes as he ruined yet another moment. Jack smirked, knelt and hugged her waist. Its only been 6 months and its the size of a watermelon. He ran out the door, while she stared at the sky.

He was scavenging for three and had no time to waste.
